[theme]
primaryColor = "#29e5e8"
backgroundColor = "#f0f9ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
fastReruns = true

[logger]
level = "info"

 